# Konfigurasi untuk runtime yang digunakan oleh aplikasi, dalam hal ini adalah runtime kustom.
runtime: custom

# Menentukan lingkungan runtime yang akan digunakan, yaitu Google App Engine Flexible Environment.
env: flex

# Nama layanan yang akan digunakan dalam App Engine.
service: restaurant-client

# Menentukan bagaimana permintaan HTTP akan ditangani. 
# Pada konfigurasi ini terdapat 2 aturan penanganan permintaan, yaitu:
handlers:
# Aturan untuk menangani permintaan yang tidak sesuai dengan aturan sebelumnya, 
  # yang akan diarahkan ke script auto.
  - url: /.*
    script: auto

# Konfigurasi auto scaling
automatic_scaling:
  target_cpu_utilization: 0.65  # Tingkat penggunaan CPU target (dalam rentang 0-1)
  min_instances: 2              # Jumlah minimum instans yang akan aktif
  max_instances: 10             # Jumlah maksimum instans yang akan aktif
  min_pending_latency: 30ms     # Latensi minimum yang diizinkan untuk permintaan tertunda
  max_pending_latency: 300ms    # Latensi maksimum yang diizinkan untuk permintaan tertunda
  automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5